Search feature
markboard-io/markboard pull request #41
Opened 2023-05-02 18:29 UTC by CulturalProfessor

Fixes(#32 )

2023-05-06 11:25 UTC, shiqimei requested changes

2023-05-06 11:25 UTC, shiqimei commented on imports/models/BoardCollection.ts
> +  searchBoards() {
make it a public method, pass `keyword: string` as parameter. use

```typescript
db.collection.find({
  $or: [
    {
      "elements.text": {
        $regex: "hello",
        $options: "i"
      }
    },
    {
      "title": {
        $regex: "hello",
        $options: "i"
      }
    }
  ]
})
```

to filter boards which `title` or text elements contains search keywords.

2023-05-06 11:25 UTC, shiqimei commented on imports/models/BoardCollection.ts
> +  searchBoards() {
check out this example: https://mongoplayground.net/p/D4PPy8eg38A

to see how i query boards which text elements or title contains "hello" keyword

hope this helps

2023-05-06 11:25 UTC, shiqimei commented on imports/services/SearchService.ts
> +    const fuse = new Fuse(boards, options)
fuse.js is great for fuzzy search in memory array. for mongodb, use `$regex` for exact search is enough currently. refer to my comments above.

remove this dependency please, if we have more time imrpove search feature, let's try to reintroduce fuse.js later.

2023-05-06 11:25 UTC, shiqimei commented on imports/subscriptions/SearchSubscriber.ts
> +class SearchSubscriberClass {
maybe for search results, we can use `searchBoards` in BoardService. we don't need to introduce `SearchSubscriber` to make the search results "reactive". it's too heavy.

we can call `Services.get('boards').searchBoards` when use typing search keywords in input box. I think this way is more simple.

2023-05-06 11:31 UTC, shiqimei commented on imports/services/ServiceManagerServer.ts
> +    this._services['search'] = new SearchService()
we can add `searchBoards` in board service, no need to add an extra service.

2023-05-07 03:25 UTC, CulturalProfessor commented on imports/pages/Board/FileExplorerPanel/FindAnything/FindAnything.module.scss
> -	background: #e7eaf1;
yes

2023-05-13 13:15 UTC, shiqimei commented
Closes #32

2023-05-13 13:19 UTC, shiqimei commented
LGTM! Thanks for your work. Let's continue on #42 .

2023-05-13 13:19 UTC, closed without merging

2023-05-13 14:57 UTC, CulturalProfessor commented
> LGTM! Thanks for your work. Let's continue on #42 .

Yeah let's improve it !!